name: enableorg
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  percent_indicator: ^4.0.1
  flutter_easyloading: ^3.0.5
  provider: ^6.0.0
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  cloud_firestore: ^4.8.2
  random_string: ^2.3.1
  file_picker: ^5.3.2
  csv: ^5.0.2
  excel: ^2.1.0
  intl: ^0.18.1
  multi_select_flutter: ^4.1.3
  country_picker: ^2.0.20
  table_calendar: ^3.0.9
  elliptic_text: ^1.0.1+9
  gradient_slider: ^1.0.1
  shared_preferences: ^2.2.2
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Cormorant Garamond
      fonts:
        - asset: fonts/CormorantGaramond-Regular.ttf