// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkcZPOMsvUT0m3XmbMquWK190DSfV0eGQ',
    appId: '1:779585827367:web:c1a64cf286947c3fa69402',
    messagingSenderId: '779585827367',
    projectId: 'enableorg-3867b',
    authDomain: 'enableorg-3867b.firebaseapp.com',
    storageBucket: 'enableorg-3867b.appspot.com',
    measurementId: 'G-WH4QKPWMR5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwsJhBPF7ncnLz0syiLxRysX8cnmaSU8c',
    appId: '1:779585827367:android:beef082f2b5f909ea69402',
    messagingSenderId: '779585827367',
    projectId: 'enableorg-3867b',
    storageBucket: 'enableorg-3867b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6OFs5K1rL8lcVtasfUoasLS84b8V3JOU',
    appId: '1:779585827367:ios:bfafa6bc2987862ca69402',
    messagingSenderId: '779585827367',
    projectId: 'enableorg-3867b',
    storageBucket: 'enableorg-3867b.appspot.com',
    iosBundleId: 'com.example.enableorg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6OFs5K1rL8lcVtasfUoasLS84b8V3JOU',
    appId: '1:779585827367:ios:1f367e064b8850aca69402',
    messagingSenderId: '779585827367',
    projectId: 'enableorg-3867b',
    storageBucket: 'enableorg-3867b.appspot.com',
    iosBundleId: 'com.example.enableorg.RunnerTests',
  );
}
